server:
  port: '8082'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8081/eureka'

spring:
  application:
    name: 'GatewayServer'

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
