server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: 'jdbc:mysql://localhost:3306/db_pagamento'
    username: 'root'
    password: '940825'
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    baselineOnMigrate: true

  application:
    name: 'pagamentos-ms'

springdoc:
  swagger-ui:
    use-root-path: true
  api-docs:
    path: '/documentacao'

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8081/eureka'
  instance:
    instance-id: ${spring.application.name}:${random.int}